package message;

public enum AccountMessageType {
	ACCOUNT_INFO, ADD_ACCOUNT, REM_ACCOUNT, ADD_USER, ADD_USER_TO_ACC, 
	REM_USER_FROM_ACC, TXF_ADMIN, CHG_PIN, CHG_PWD, USER_INFO, CHK_OWN,
	CHK_ACC_ADM, CHK_DUP, CHK_ITSELF;
}
